server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Spostiamo il resolver qui per renderlo disponibile a tutto il server
    resolver 169.254.169.253 valid=30s;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;
    }

    # Proxy per API Gateway (Verifica bene il nome dal comando CloudShell!)
    location /property/ {
        # Usiamo 'set' per evitare il crash all'avvio (Host not found)
        set $api_gateway_endpoint "http://api-gateway.dieti.local.dietiestates.local:8082";
        proxy_pass $api_gateway_endpoint;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy per User Service
    location /user/ {
        set $user_service_endpoint "http://user-service.dietiestates.local:8080";
        proxy_pass $user_service_endpoint;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}