server.port=${PORT:8080}
spring.application.name=user-service
server.servlet.context-path=/user

# JWT Configuration
jwt.private.key=${JWT_PRIVATE_KEY}

jwt.cookie.name=${REFRESH_COOKIE_NAME:refreshToken}
jwt.cookie.path=${REFRESH_COOKIE_PATH:/}

jwt.cookie.samesite=${REFRESH_COOKIE_SAMESITE:Lax}
jwt.cookie.secure=${REFRESH_COOKIE_SECURE:false}

jwt.issuer=${JWT_ISS:dietiestates-auth}
jwt.audience=${JWT_AUD:dietiestates-app}

jwt.ttl.access=${JWT_ACCESS_TTL:3600000}
jwt.ttl.refresh=${JWT_REFRESH_TTL:2592000000}

# Database Configuration (PostgreSQL/H2)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hikari Connection Pool Settings for Render Free Tier
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Google Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


# GitHub Configuration
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}


# 1. Fondamentale per Gateway: istruisce Spring a usare l'Host del Gateway (8082) invece di quello interno (8080)
server.forward-headers-strategy=framework

# 2. Specifica esplicitamente il redirect URI atteso
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8082/user/login/oauth2/code/google
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8082/user/login/oauth2/code/github
# 3. Definisci gli Scope 
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.github.scope=read:user,user:email

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.dietiestates=DEBUG