server.port=8081
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.gcbdwehlgezxbwntveik
spring.datasource.password=Santagnello1

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Mail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dietiestates@gmail.com
spring.mail.password=dieti
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==== JWT (configurazione) ====
jwt.private-pem=${JWT_PRIVATE_PEM_B64:file:.gitignore/private.pem.b64}
jwt.public-pem=${JWT_PUBLIC_PEM_B64:file:.gitignore/public.pem.b64}


jwt.iss=${JWT_ISS:ingsw-auth}
jwt.aud=${JWT_AUD:ingsw-apis}
jwt.access-ttl=${JWT_ACCESS_TTL:15m}
jwt.refresh-ttl=${JWT_REFRESH_TTL:30d}
jwt.kid=${JWT_KID:current-001}

# Cookie del refresh
jwt.refresh-cookie-name=${REFRESH_COOKIE_NAME:refreshToken}
jwt.refresh-cookie-path=${REFRESH_COOKIE_PATH:/api/v1/user/refresh}
jwt.refresh-cookie-same-site=${REFRESH_COOKIE_SAMESITE:Strict}
jwt.refresh-cookie-secure=${REFRESH_COOKIE_SECURE:true}
jwt.jwks-max-age-seconds=${JWKS_CACHE_MAXAGE_SECONDS:300}

# ==== DB (sposta credenziali su ENV/Secret) ====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ==== Mail (sposta credenziali su ENV/Secret) ====
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}

# (Se stai dietro proxy/ingress e vuoi cookie Secure corretti)
server.forward-headers-strategy=framework
