server.port=8081
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.gcbdwehlgezxbwntveik
spring.datasource.password=Santagnello1

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Mail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dietiestates@gmail.com
spring.mail.password=dieti
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true