server.port=${PORT:8082}
spring.application.name=api-gateway

# ALLOWED_ORIGINS
ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000,https://dieti-estates25-demeo-carrese.vercel.app,https://dieti-estates25-demeo-carrese*.vercel.app

# JWT Configuration
jwt.public.key=${JWT_PUBLIC_KEY}

# Eureka Configuration (Optional placeholder)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Routes Configuration

