server.port=8082
spring.application.name=property-service

# ==== DATABASE (Supabase) ====

# ==== DB (sposta credenziali su ENV/Secret) ====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

server.servlet.context-path=/property-service

# ==== JWT VALIDATION ====
jwt.public-pem=${JWT_PUBLIC_PEM_B64:file:config/public.pem.b64}

jwt.iss=ingsw-auth
jwt.aud=ingsw-apis


