name: Build and Push to AWS ECR

on:
  push:
    branches: [ "mainUpdate" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push All Images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Frontend
          docker build -t $ECR_REGISTRY/dieti-frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push $ECR_REGISTRY/dieti-frontend:latest
          
          # Gateway
          docker build -t $ECR_REGISTRY/dieti-api-gateway:latest -f ./backend/api-gateway/Dockerfile ./backend/api-gateway
          docker push $ECR_REGISTRY/dieti-api-gateway:latest
          
          # User Service
          docker build -t $ECR_REGISTRY/dieti-user-service:latest -f ./backend/user-service/Dockerfile ./backend/user-service
          docker push $ECR_REGISTRY/dieti-user-service:latest
          
          # Property Service
          docker build -t $ECR_REGISTRY/dieti-property-service:latest -f ./backend/property-service/Dockerfile ./backend/property-service
          docker push $ECR_REGISTRY/dieti-property-service:latest
      - name: Force ECS Update
        run: |
          aws ecs update-service --cluster dietiestates-cluster --service frontend --force-new-deployment